### ISSUE TITLE
How to run test properly

### ISSUE THREAD

**Issue by yccheok** [stepstone-tech/android-material-stepper#147]
I had downloaded master branch of this repo.

I tried to run test by right click on com.stepstone.stepper (test), then click on `Run Test in 'stepper''`

12 failed out of 16 tests.

For every failed test, the log is

    android.content.res.Resources$NotFoundException: Resource ID #0x7f080000

	at android.content.res.Resources.getValue(Resources.java:1014)
	at android.content.res.Resources.getBoolean(Resources.java:796)
	at com.stepstone.stepper.internal.widget.pagetransformer.StepPageTransformerFactory.createPageTransformer(StepPageTransformerFactory.java:32)
	at com.stepstone.stepper.internal.widget.pagetransformer.StepPageTransformerFactoryTest.Should return 'null' by default on JellyBean_MR1(StepPageTransformerFactoryTest.kt:36)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:487)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:209)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:109)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:36)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:63)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

Line `com.stepstone.stepper.internal.widget.pagetransformer.StepPageTransformerFactory.createPageTransformer(StepPageTransformerFactory.java:32` is

    boolean rtlEnabled = context.getResources().getBoolean(R.bool.ms_rtlEnabled);

I'm using Android Studio 2.3.2. I had downloaded Kotlin plugin so that it will work with some Kotlin files for this repo

Any idea why unit test in failing in my local?

**Comment by zawadz88** [comment]
Hi,
Please make sure you set your working directory correctly: http://robolectric.org/getting-started/

**Comment by zawadz88** [comment]
Hi @yccheok,
Were you able to run the tests?

**Comment by yccheok** [comment]
@zawadz88 sorry. I haven't tested it out yet as I'm focus on other project recently. will test run it soon...

**Comment by yccheok** [comment]
@zawadz88 Not really. After reading http://robolectric.org/getting-started/ and http://robolectric.org/configuring/ , doesn't help much.

I'm developing in Window machine, with latest Android Studio.

**Comment by zawadz88** [comment]
@yccheok, could you share the screenshot of the test configuration in Android Studio? https://developer.android.com/studio/run/rundebugconfig.html#about
Also, does it work for you when you run it from the command line i.e. `gradlew.bat testDebugUnitTest`?

**Comment by zawadz88** [comment]
Hi @yccheok,
Any luck?

**Comment by yccheok** [comment]
@zawadz88 

Sorry. Since after we have successful apply your lib into our project with 0 issue, we move on to other area of the project and didn't look into this anymore.

Able to run the test is no longer our concern anymore. Is this your concern too? If yes, I can spare some time to look into it. If not, I think we can close this issue :)
