### ISSUE TITLE
Facing problem when changing Step fragment dynamically

### ISSUE THREAD

**Issue by yccheok** [stepstone-tech/android-material-stepper#182]
We have several different different scenarios based on user selection in the step fragments.

The navigation should be

A -> B -> C -> D -> E -> F

Based on certain selection in the step fragment, the navigation can be changed dynamically to

A -> E -> F

First, we have the following logic in adapter

```
public class CreateLiveAccountStepperAdapter extends AbstractFragmentStepAdapter {
    @Override
    public Step createStep(int position) {
        Step step = null;

        if (basedOnUserSelectionInStepFragment()) {
            switch (position) {
                case 0:
                    step = new CountryCitizenshipStepFragment();
                    break;
                case 1:
                    step = new GenderStepFragment();
                    break;
                ...
            }
        } else {
            switch (position) {
                case 0:
                    step = new CountryCitizenshipStepFragment();
                    break;
                case 1:
                    step = new ResidentialCityStateZipStepFragment();
                    break;
                ...
            }
        }
        
        return step;
    }
    
    @Override
    public int getCount() {
        if (basedOnUserSelection()) {
            return 20;
        }

        return 10;
    }
}
```

The above code wouldn't work well even after calling `notifyDataSetChange`. The reason is that, even you back n forth several times to the same Nth step, `createStep` will only be called 1 time for a same `int position`.

After looking at

https://github.com/stepstone-tech/android-material-stepper/issues/47

https://github.com/stepstone-tech/android-material-stepper/issues/39

I thought

1. Assigning a new adapter to stepper layout.
2. Set the desired step to the stepper layout after assigning the new adapter.

But, if I change the adapter when I am in Nth page, I will get the following error

> java.lang.IllegalStateException: FragmentManager is already executing transactions
>     at android.support.v4.app.FragmentManagerImpl.ensureExecReady(FragmentManager.java:1956)
>     at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1980)
>     at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
>     at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
>     at android.support.v4.view.ViewPager.setAdapter(ViewPager.java:513)
>     at com.stepstone.stepper.StepperLayout.setAdapter(StepperLayout.java:318)
> 
Anyone has experience in doing similar stuff? Mind to share your experience?

**Comment by yccheok** [comment]
Currently, `AbstractFragmentStepAdapter` is using `FragmentPagerAdapter` as its underlying class.

Is it possible that we can solve this problem using `FragmentStatePagerAdapter`?

https://stackoverflow.com/a/10852046/72437

**Comment by yccheok** [comment]
I just did a quick hacking, in order for us to "skip" steps. i.e., from A to E instead of A to B

https://github.com/yccheok/android-material-stepper/commit/4de68f067c45e819584a2dd2715fb5a928b8815e

Is not a clean solution, as it will break current existing code due to new methods in interface.

**Comment by zawadz88** [comment]
Hi @yccheok,
You can use any adapter which implements `StepAdapter`. So in theory `FragmentStatePagerAdapter` should work as well. Although you will have to add some extra logic to find the steps as in `AbstractFragmentStepAdapter#findStep(int)` since with vanilla `FragmentStatePagerAdapter` you cannot find Fragments by tag.

**Comment by zawadz88** [comment]
Hi @yccheok,
Any luck?

**Comment by Rainer-Lang** [comment]
I have the same scenario as @yccheok 
User could make decision in step 3 and this decides if there is a step 4 or not.
I'm still not sure what is a good solution.

**Comment by Rainer-Lang** [comment]
@yccheok Is it possible to disable a step?

**Comment by yccheok** [comment]
Hey guys, sorry for late respond as I'm pretty tied up with the project.

I had successful roll out the project using this wonderful lib.

My scenario case is being used in stock market account opening (which contains 20+ steps!)

https://plus.google.com/116311379832695909648/posts/XvUUKX93Bsf

I don't have a clean solution. As I mentioned in previous thread, I did some "hacked" modification on `Step` interface.

https://github.com/yccheok/android-material-stepper/commit/4de68f067c45e819584a2dd2715fb5a928b8815e

Instead of advancing forward 1 step, or backward 1 step, `Step` implementer need to provide how many N step to be advanced (or backward) based on user UI selection.

For instance, this is one of my implementation

    @Override
    public int getBackOffset() {
        return 1;
    }

    @Override
    public int getNextOffset() {
        if (Utils.isEmploymentStatusEmployed()) {
            return 1;
        }
        return 6;
    } 

It is not a very clean and perfect solution. As from user perspective, he still can visualize, the unwanted Step page, slide across (in a very fast speed) his visual region.

But, so far we are happy with the approach. As from business perspective, we can get a reasonable signup rate :)

Talk to me if you need more info

**Comment by Rainer-Lang** [comment]
@yccheok Maybe it's possible to make a PR - if the contributors want it? Do you have things even changed?

**Comment by yccheok** [comment]
I don't think the contributors want it, as the change is being done on interface. Existing code will break.

**Comment by Rainer-Lang** [comment]
@yccheok Yeah, could be. I think such a feature is simply missing.....

**Comment by burakremzisenel** [comment]
You need to override getItemId.  It's only working solution for me after trying everything.

> long getItemId (int position)
> 
> Return a unique identifier for the item at the given position.
> 
> The default implementation returns the given position. **Subclasses should override this method if the positions of items can change.**

Just provide a unique id to each fragment and you're done.
