### ISSUE TITLE
layoutinflator error in ms_stepperType set to tabs on api19

### ISSUE THREAD

**Issue by tmediaa** [stepstone-tech/android-material-stepper#193]
hi, when i use android material stepper in android api above 19 there are no problem, but problem occur when app run on api19 targets ,
logcat for this error is : 
`
08-26 10:38:59.541 15311-15311/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: tmediaa.ir.stepper, PID: 15311
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{tmediaa.ir.stepper/tmediaa.ir.stepper.MainActivity}: android.view.InflateException: Binary XML file line #3: Error inflating class com.stepstone.stepper.internal.widget.StepTab
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: android.view.InflateException: Binary XML file line #3: Error inflating class com.stepstone.stepper.internal.widget.StepTab
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                       at com.stepstone.stepper.internal.widget.TabsContainer.createStepTab(TabsContainer.java:184)
                                                       at com.stepstone.stepper.internal.widget.TabsContainer.setSteps(TabsContainer.java:158)
                                                       at com.stepstone.stepper.internal.type.TabsStepperType.onNewAdapter(TabsStepperType.java:86)
                                                       at com.stepstone.stepper.StepperLayout.setAdapter(StepperLayout.java:330)
                                                       at com.stepstone.stepper.StepperLayout.setAdapter(StepperLayout.java:351)
                                                       at tmediaa.ir.stepper.MainActivity.onCreate(MainActivity.java:23)
                                                       at android.app.Activity.performCreate(Activity.java:5231)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                       at java.lang.reflect.Constructor.constructNative(Native Method)
                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:594)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:469) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                       at com.stepstone.stepper.internal.widget.TabsContainer.createStepTab(TabsContainer.java:184) 
                                                       at com.stepstone.stepper.internal.widget.TabsContainer.setSteps(TabsContainer.java:158) 
                                                       at com.stepstone.stepper.internal.type.TabsStepperType.onNewAdapter(TabsStepperType.java:86) 
                                                       at com.stepstone.stepper.StepperLayout.setAdapter(StepperLayout.java:330) 
                                                       at com.stepstone.stepper.StepperLayout.setAdapter(StepperLayout.java:351) 
                                                       at tmediaa.ir.stepper.MainActivity.onCreate(MainActivity.java:23) 
                                                       at android.app.Activity.performCreate(Activity.java:5231) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                    Caused by: android.content.res.Resources$NotFoundException: File res/drawable-xxhdpi-v4/ms_vector_circle_24dp.png from xml type xml resource ID #0x7f02005d
                                                       at android.content.res.Resources.loadXmlResourceParser(Resources.java:2356)
                                                       at android.content.res.Resources.loadXmlResourceParser(Resources.java:2311)
                                                       at android.content.res.Resources.getXml(Resources.java:988)
                                                       at android.support.graphics.drawable.VectorDrawableCompat.create(VectorDrawableCompat.java:586)
                                                       at android.support.graphics.drawable.AnimatedVectorDrawableCompat.inflate(AnimatedVectorDrawableCompat.java:387)
                                                       at android.support.graphics.drawable.AnimatedVectorDrawableCompat.createFromXmlInner(AnimatedVectorDrawableCompat.java:179)
                                                       at android.support.graphics.drawable.AnimatedVectorDrawableCompat.create(AnimatedVectorDrawableCompat.java:159)
                                                       at com.stepstone.stepper.internal.widget.StepTab.createAnimatedVectorDrawable(StepTab.java:205)
                                                       at com.stepstone.stepper.internal.widget.StepTab.createCircleToWarningDrawable(StepTab.java:191)
                                                       at com.stepstone.stepper.internal.widget.StepTab.<init>(StepTab.java:119)
                                                       at com.stepstone.stepper.internal.widget.StepTab.<init>(StepTab.java:97)
                                                       at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:469) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                       at com.stepstone.stepper.internal.widget.TabsContainer.createStepTab(TabsContainer.java:184) 
                                                       at com.stepstone.stepper.internal.widget.TabsContainer.setSteps(TabsContainer.java:158) 
                                                       at com.stepstone.stepper.internal.type.TabsStepperType.onNewAdapter(TabsStepperType.java:86) 
                                                       at com.stepstone.stepper.StepperLayout.setAdapter(StepperLayout.java:330) 
                                                       at com.stepstone.stepper.StepperLayout.setAdapter(StepperLayout.java:351) 
                                                       at tmediaa.ir.stepper.MainActivity.onCreate(MainActivity.java:23) 
                                                       at android.app.Activity.performCreate(Activity.java:5231) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                    Caused by: java.io.FileNotFoundException: Corrupt XML binary file
                                                       at android.content.res.AssetManager.openXmlAssetNative(Native Method)
                                                       at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:488)
                                                       at android.content.res.Resources.loadXmlResourceParser(Resources.java:2338)
                                                       at android.content.res.Resources.loadXmlResourceParser(Resources.java:2311) 
                                                       at android.content.res.Resources.getXml(Resources.java:988) 
                                                       at android.support.graphics.drawable.VectorDrawableCompat.create(VectorDrawableCompat.java:586) 
                                                       at android.support.graphics.drawable.AnimatedVectorDrawableCompat.inflate(AnimatedVectorDrawableCompat.java:387) 
                                                       at android.support.graphics.drawable.AnimatedVectorDrawableCompat.createFromXmlInner(AnimatedVectorDrawableCompat.java:179) 
                                                       at android.support.graphics.drawable.AnimatedVectorDrawableCompat.create(AnimatedVectorDrawableCompat.java:159) 
                                                       at com.stepstone.stepper.internal.widget.StepTab.createAnimatedVectorDrawable(StepTab.java:205) 
                                                       at com.stepstone.stepper.internal.widget.StepTab.createCircleToWarningDrawable(StepTab.java:191) 
                                                       at com.stepstone.stepper.internal.widget.StepTab.<init>(StepTab.java:119) 
                                                       at com.stepstone.stepper.internal.widget.StepTab.<init>(StepTab.java:97) 
                                                       at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:469) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                       at com.stepstone.stepper.internal.widget.TabsContainer.createStepTab(TabsContainer.java:184) 
                                                       at com.stepstone.stepper.internal.widget.TabsContainer.setSteps(TabsContainer.java:158) 
                                                       at com.stepstone.stepper.internal.type.TabsStepperType.onNewAdapter(TabsStepperType.java:86) 
                                                       at com.stepstone.stepper.StepperLayout.setAdapter(StepperLayout.java:330) 
                                                       at com.stepstone.stepper.StepperLayout.setAdapter(StepperLayout.java:351) 
                                                       at tmediaa.ir.stepper.MainActivity.onCreate(MainActivity.java:23) 
                                                       at android.app.Activity.performCreate(Activity.java:5231) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                       at dalvik.system.NativeStart.main(Native Method) `

**Comment by zawadz88** [comment]
Hi @tmediaa,
What Build tools/support library version are you using in your project?
Also, which library version are you using? Is it something you can reproduce in the sample app as well?

**Comment by tmediaa** [comment]
version of build tools in project is: v25.3.1 

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:multidex:1.0.0'
    compile 'com.android.support:cardview-v7:25.3.1'
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support:percent:25.3.1'
    compile 'com.android.support:design:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.0-alpha9'
    compile 'com.google.android.gms:play-services-location:7.3.0'
    compile 'ch.acra:acra:4.8.5'
    testCompile 'junit:junit:4.12'
}

```
@zawadz88  it is sample app : 
https://github.com/tmediaa/android-material-stepper

**Comment by zawadz88** [comment]
The minimum required version by the lib is `25.4.0`. This is in the release notes (https://github.com/stepstone-tech/android-material-stepper/releases/tag/v4.0.0), however I think this should be added to the README file so that there is no confusion.
If for some reason you cannot update to `25.4.0` you can use an older version of the library e.g. `3.3.0` which used `25.3.1`.
Please let me know if this helps.

**Comment by tmediaa** [comment]
in version 3.3 of library also sample problem occured

sample app link : https://github.com/tmediaa/material-stepper-3.3

**Comment by zawadz88** [comment]
In https://github.com/tmediaa/material-stepper-3.3/blob/master/app/build.gradle you're missing `vectorDrawables.useSupportLibrary = true` in `android -> defaultConfig`. See if this helps please.

**Comment by tmediaa** [comment]
problem not solve after add `vectorDrawables.useSupportLibrary = true`
logcat problem is it:

```

08-27 12:55:33.680 5921-5921/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: tmediaa.ir.stepper, PID: 5921
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{tmediaa.ir.stepper/tmediaa.ir.stepper.MainActivity}: android.view.InflateException: Binary XML file line #3: Error inflating class com.stepstone.stepper.internal.widget.StepTab
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: android.view.InflateException: Binary XML file line #3: Error inflating class com.stepstone.stepper.internal.widget.StepTab
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                     at com.stepstone.stepper.internal.widget.TabsContainer.createStepTab(TabsContainer.java:183)
                                                     at com.stepstone.stepper.internal.widget.TabsContainer.setSteps(TabsContainer.java:157)
                                                     at com.stepstone.stepper.internal.type.TabsStepperType.onNewAdapter(TabsStepperType.java:85)
                                                     at com.stepstone.stepper.StepperLayout.setAdapter(StepperLayout.java:321)
                                                     at com.stepstone.stepper.StepperLayout.setAdapter(StepperLayout.java:342)
                                                     at tmediaa.ir.stepper.MainActivity.onCreate(MainActivity.java:23)
                                                     at android.app.Activity.performCreate(Activity.java:5231)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233) 
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:136) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                     at java.lang.reflect.Constructor.constructNative(Native Method)
                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:594)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:469) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                     at com.stepstone.stepper.internal.widget.TabsContainer.createStepTab(TabsContainer.java:183) 
                                                     at com.stepstone.stepper.internal.widget.TabsContainer.setSteps(TabsContainer.java:157) 
                                                     at com.stepstone.stepper.internal.type.TabsStepperType.onNewAdapter(TabsStepperType.java:85) 
                                                     at com.stepstone.stepper.StepperLayout.setAdapter(StepperLayout.java:321) 
                                                     at com.stepstone.stepper.StepperLayout.setAdapter(StepperLayout.java:342) 
                                                     at tmediaa.ir.stepper.MainActivity.onCreate(MainActivity.java:23) 
                                                     at android.app.Activity.performCreate(Activity.java:5231) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233) 
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:136) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                  Caused by: java.lang.NumberFormatException: Invalid int: "M 12,0 C 2.7795742,0.00373968 -2.992,9.9726253 1.5957031,17.970703 C 3.7552647,21.714092 7.7149163,23.999508 12,24 c 4.279501,-0.0061 8.231906,-2.290736 10.373047,-5.996094 C 26.973642,9.9673078 21.210345,0.01252246 12,0 M 12.947579,15.161259 l 0,0 0,0 0,0 0,0 Z m 0,-3.790315 l 0,0 0,0 0,0 0,0 Z"
                                                     at java.lang.Integer.invalidInt(Integer.java:137)
                                                     at java.lang.Integer.parse(Integer.java:374)
                                                     at java.lang.Integer.parseInt(Integer.java:365)
                                                     at com.android.internal.util.XmlUtils.convertValueToInt(XmlUtils.java:122)
                                                     at android.content.res.TypedArray.getInt(TypedArray.java:255)
                                                     at android.animation.AnimatorInflater.loadAnimator(AnimatorInflater.java:258)
                                                     at android.animation.AnimatorInflater.loadObjectAnimator(AnimatorInflater.java:161)
                                                     at android.animation.AnimatorInflater.createAnimatorFromXml(AnimatorInflater.java:117)
                                                     at android.animation.AnimatorInflater.createAnimatorFromXml(AnimatorInflater.java:93)
                                                     at android.animation.AnimatorInflater.loadAnimator(AnimatorInflater.java:72)
                                                     at android.support.graphics.drawable.AnimatedVectorDrawableCompat.inflate(AnimatedVectorDrawableCompat.java:408)
                                                     at android.support.graphics.drawable.AnimatedVectorDrawableCompat.createFromXmlInner(AnimatedVectorDrawableCompat.java:179)
                                                     at android.support.graphics.drawable.AnimatedVectorDrawableCompat.create(AnimatedVectorDrawableCompat.java:159)
                                                     at com.stepstone.stepper.internal.widget.StepTab.createAnimatedVectorDrawable(StepTab.java:211)
                                                 	at com.stepstone.stepper.internal.widget.StepTab.createCircleToWarningDrawa
```

**Comment by zawadz88** [comment]
It is working for me on KitKat with the changes I proposed.
1. Change `compile 'com.android.support:appcompat-v7:25.3.1'` to `compile 'com.android.support:appcompat-v7:25.4.0'`
2. Add `vectorDrawables.useSupportLibrary = true` in `android` -> `defaultConfig`.

**Comment by zawadz88** [comment]
Note: this is not actually happening if you use the library as a Gradle dependency from JCenter - it's happening in a repo with copied classes.
