### ISSUE TITLE
Android API 19: Binary XML file line #17: invalid drawable tag vector

### ISSUE THREAD

**Issue by wirthual** [stepstone-tech/android-material-stepper#26]
Hello stepstone team,
thanks for sharing this library. I want to use it with API Level 19 and I always get this error:
Binary XML file line #17: invalid drawable tag vector
I use:     compile 'com.android.support:appcompat-v7:25.0.0'
Also tried: vectorDrawables.useSupportLibrary = true

But didn't solve the Problem.

Seems to be this issue:[stackoverflow]( http://stackoverflow.com/questions/35819290/invalid-drawable-tag-vector)

Can you say something about supported API Levels or do you know how to fix this error?
Here the complete output of console:
```
Unable to start activity ComponentInfo{com.projecttango.experiments.planefittingsample/com.projecttango.examples.java.planefitting.ui.stepper.StepperActivity}: 
android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f020052
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2196)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2246)
at android.app.ActivityThread.access$800(ActivityThread.java:136)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1197)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5030)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f020052
at android.content.res.Resources.loadDrawable(Resources.java:2096)
at android.content.res.Resources.getDrawable(Resources.java:700)
at android.support.v7.widget.VectorEnabledTintResources.superGetDrawable(VectorEnabledTintResources.java:74)
at android.support.v7.widget.AppCompatDrawableManager.onDrawableLoadedFromResources(AppCompatDrawableManager.java:435)
at android.support.v7.widget.VectorEnabledTintResources.getDrawable(VectorEnabledTintResources.java:67)
at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:374)
at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:200)
at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:188)
at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:723)
at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:193)
at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81)
at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:127)
at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:147)
at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:27)
at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:53)
at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:205)
at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185)
at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:525)
at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:74)
                                                                                                     at com.projecttango.examples.java.planefitting.ui.stepper.StepperActivity.onCreate(StepperActivity.java:50)
at android.app.Activity.performCreate(Activity.java:5231)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2160)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2246) 
at android.app.ActivityThread.access$800(ActivityThread.java:136) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1197) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:136) 
at android.app.ActivityThread.main(ActivityThread.java:5030) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
at by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector
at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
at android.content.res.Resources.loadDrawable(Resources.java:2092)
at android.content.res.Resources.getDrawable(Resources.java:700) 
at android.support.v7.widget.VectorEnabledTintResources.superGetDrawable(VectorEnabledTintResources.java:74) 
at android.support.v7.widget.AppCompatDrawableManager.onDrawableLoadedFromResources(AppCompatDrawableManager.java:435) 
at android.support.v7.widget.VectorEnabledTintResources.getDrawable(VectorEnabledTintResources.java:67) 
at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:374) 
at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:200) 
at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:188) 
at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:723) 
at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:193) 
at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81) 
at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:127) 
at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:147) 
at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:27) 
at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:53) 
at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:205) 
at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185) 
at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:525) 
at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:74) 
                                                                                                     at com.projecttango.examples.java.planefitting.ui.stepper.StepperActivity.onCreate(StepperActivity.java:50) 
at android.app.Activity.performCreate(Activity.java:5231) 
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2160) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2246) 
at android.app.ActivityThread.access$800(ActivityThread.java:136) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1197) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:136) 
at android.app.ActivityThread.main(ActivityThread.java:5030) 
at java.lang.reflect.Method.invoke(Native Method)
```

Thank you.

**Comment by zawadz88** [comment]
Hi. Could you share a bit more about your build.gradle? Are you using the latest build tools/Gradle plugin? The library supports API 14 so it should work with API 19 without any issues (we checked ;) )

**Comment by wirthual** [comment]
Hi,
Thank you for your help. As you mentioned I didn't use the current build tools. So with build tools v 25.0.0 it works like charm. I can proof the library is working on API level 19 now as well :+1:

**Comment by zawadz88** [comment]
I'm glad it works :)

**Comment by naisanhamza88** [comment]
same error in Android API 19

**Comment by wirthual** [comment]
Which version of build tools are you using?

**Comment by naisanhamza88** [comment]
buildToolsVersion "25.0.2"

**Comment by zawadz88** [comment]
@naisanhamza88 could you share a bit more from your build.gradle? What support library version you're using,  which Material Stepper library version etc?

**Comment by odoo-winspireweb** [comment]
What about android studio 3.0 + .... it uses build tools > 26.0.2 / whatever is latest stable one ... @naisanhamza88  @wirthual How can we deal with that?

**Comment by devang-dreambits** [comment]
What about android studio 3.0 + .... it uses build tools > 26.0.2 / whatever is latest stable one ... @naisanhamza88 @wirthual How can we deal with that?
